### ISSUE TITLE
Tag geographical data with feature IDs

### ISSUE THREAD

**Issue by dapetcu21** [code4romania/rezultate-vot-client#15]
- [x] Tag the data with database IDs and names (@catileptic)
- [x] Simplify geometry and export GeoJSON (@dapetcu21)
- [x] Deploy files to S3 (@RaduCStefanescu)
- [x] Change default hosted files URL in reusable-components (@dapetcu21)

**Comment by RaduCStefanescu** [comment]
All the issues are fixed.
