### ISSUE TITLE
[Newsfeed] Video embed does not stay in container

### ISSUE THREAD

**Issue by overeha** [code4romania/rezultate-vot-client#31]
The video embeds do not respect container margins. 

![image](https://user-images.githubusercontent.com/45068169/94279456-ca9f6180-ff54-11ea-81eb-e2837138ee2c.png)

**Comment by dapetcu21** [comment]
Yes, because the video embed has a fixed width attribute. Remove it or set it to `width="100%"` and it will look fine.
