### ISSUE TITLE
Author pictures in Newsfeed appear stretched

### ISSUE THREAD

**Issue by overeha** [code4romania/rezultate-vot-client#35]
Make sure the newsfeed pictures are resized properly

![image](https://user-images.githubusercontent.com/45068169/94287835-751c8200-ff5f-11ea-8679-a0ef453b61e9.png)

**Comment by RazvanCiuca** [comment]
This happens because the picture isn't square. Do we want to do anything about it?

**Comment by Utwo** [comment]
Please update the uploaded picture with a 32x32 one.

**Comment by overeha** [comment]
![oliviaverehasite](https://user-images.githubusercontent.com/45068169/94360064-7363d300-00b3-11eb-9369-027a1b5410e5.png)

**Comment by overeha** [comment]
Radu is not posting in the newsfeed so no need to fix

**Comment by Utwo** [comment]
Done! The image was updated on S3 bucket
