### ISSUE TITLE
Add new expert in About page

### ISSUE THREAD

**Issue by overeha** [code4romania/rezultate-vot-client#53]
Add a new expert in the [About page](https://staging.rezultatevot.ro/about). 

He needs to be added in the 4th position after Bogdan Ivanel 

**Mircea Kivu**

Mircea Kivu sociology, master în Demografie şi Ştiinţe Sociale la Ecole des Hautes Etudes en Sciences Sociales – Paris. Este cunoscut ca autor al mai multor lucrǎri şi articole de sociologie, principalul sǎu domeniu de expertizǎ fiind cercetarea opiniei publice. Din 1992, a deţinut funcţii de conducere în mai multe institute de cercetare (director de cercetare, apoi CEO la IMAS Marketing şi Sondaje, vice-preşedinte pentru Cercetare despre Cercetare la Ipsos Interactive Services, director de operaţiuni la Mercury Research).). A fost membru al Corpului expertilor electorali din România.

![mirceakivu](https://user-images.githubusercontent.com/45068169/94339716-a56a2c00-0004-11eb-9e6a-9c4b0ed7db5a.jpg)

**Comment by catileptic** [comment]
Closed by [be461733571cdfa8157a1d43c8a7ba3a33d02f9f](https://github.com/code4romania/rezultate-vot-client/commit/be461733571cdfa8157a1d43c8a7ba3a33d02f9f)
