### ISSUE TITLE
Change label in header menu 

### ISSUE THREAD

**Issue by overeha** [code4romania/rezultate-vot-client#54]
Change "Istoric alegeri" with "Date alegeri"
![image](https://user-images.githubusercontent.com/45068169/94340156-30005a80-0008-11eb-97d2-e74e822a2c75.png)

**Comment by catileptic** [comment]
closed by [4d77299130f41c70aac5c3e19f3c63aaf2ee44f0](https://github.com/code4romania/rezultate-vot-client/commit/4d77299130f41c70aac5c3e19f3c63aaf2ee44f0)
