### ISSUE TITLE
Add new expert in the About page 

### ISSUE THREAD

**Issue by overeha** [code4romania/rezultate-vot-client#55]
Add Maria Krause as an expert in the About page in the second position after Claudiu Tufiș

Maria Krause

Maria Krause este expert electoral cu o experienţă de peste 14 ani în observarea alegerilor în ţară şi în străinătate. A participat la misiuni de observarea alegerilor ale Oficiului OSCE pentru Instituţii Democratice şi Drepturile Omului (OSCE/ODIHR) în Kirghizstan, Kazakhstan, Macedonia de Nord, Serbia, Moldova, Letonia, Bulgaria, Ucraina, Albania, Muntenegru şi la misiuni organizate de Carter Center în Nepal, Mozambic şi Guyana. În România a făcut parte în 2014 dintre coordonatorii proiectelor organizate de Expert Forum pentru observarea alegerilor europarlamentare şi de Centrul pentru Resurse Civice pentru observarea alegerilor prezidenţiale, iar din 2016 participă ca expert electoral la proiectul FiecareVot.

![mariakrausesite](https://user-images.githubusercontent.com/45068169/94344625-4e2a8280-0029-11eb-996c-bb9f6786393b.png)

**Comment by catileptic** [comment]
Done in [this commit](https://github.com/code4romania/rezultate-vot-client/commit/f121a283fb879af5cdaa2e62c7c832daa6da37a5)
