### ISSUE TITLE
Add a link with anchor in main menu

### ISSUE THREAD

**Issue by overeha** [code4romania/rezultate-vot-client#72]
Can we add an anchor link in the menu? 

It should say ”Live newsfeed” and jump me to the live feed section of the platform. 

![image](https://user-images.githubusercontent.com/45068169/94368893-5c42d680-00ef-11eb-9b78-057bdcea65f7.png)

**Comment by popsorina** [comment]
I will take this one

**Comment by RaduCStefanescu** [comment]
All yours @popsorina
