### ISSUE TITLE
Create staging and prod environments

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/rezultate-vot-client#82]
Create `develop` branch and create GHA pipeline to deploy this branch to staging environment.

**Comment by Utwo** [comment]
I can take this

**Comment by Utwo** [comment]
Do we want to have a staging env on AWS or Vercel?

**Comment by RaduCStefanescu** [comment]
Currently we have the staging environment on AWS, but I would like to move it to Vercel.

**Comment by RaduCStefanescu** [comment]
Reopening this for Vercel deployment.

**Comment by dapetcu21** [comment]
Sorry. Didn't notice that before closing it

**Comment by cipick** [comment]
@RaduCStefanescu i can see that you fixed this issue [.github/workflows](https://github.com/code4romania/rezultate-vot-client/tree/develop/.github/workflows
)
happy to close it?

**Comment by RaduCStefanescu** [comment]
Thanks for the reminder @cipick 
@utwo how about moving the development/staging environment on Vercel? Do you have the time to handle this task?

**Comment by Utwo** [comment]
Yes, sure!

**Comment by Utwo** [comment]
We have automatic deploys to Vercel!https://rezultate-vot-client.vercel.app
