### ISSUE TITLE
Modify localities drop down to handle the electionId/ballotId as well

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/rezultate-vot-client#83]
When we query for the localities, we need to filter based on the electionId and ballotId, so that only localities that have results for that election should be present in the dropdown.

**Comment by dapetcu21** [comment]
I'll take this. Should be a small change. Only `ballotId` is needed, since this data should be tied to the ballot, not the election. (Also, we don't always have `electionId` on hand in the frontend).

**Comment by RaduCStefanescu** [comment]
Soundds good, yes, the ballotId is the only one we will need. Will make sure the backend is ready to accept the new change.

**Comment by dapetcu21** [comment]
Done: https://github.com/code4romania/reusable-components/pull/80

It's forwards and backwards compatible. The backend just ignores the new param for now so nothing should break.
