### ISSUE TITLE
Zoom in and lock the map

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/rezultate-vot-client#85]
For national, county and locality views, zoom in on the map and lock the scrolling and zoom level.

**Comment by dapetcu21** [comment]
I'll take this next week.

**Comment by dapetcu21** [comment]
As discussed on Slack:

* Everything in https://github.com/code4romania/reusable-components/pull/73
* Zoom is locked for all map overlays except `diaspora`/`diaspora_country`
* Zoom on selected country in `diaspora_country` mode
